
package com.sforce.soap.enterprise;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Soap", targetNamespace = "urn:enterprise.soap.sforce.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.sforce.soap.enterprise.ObjectFactory.class,
    com.sforce.soap.enterprise.fault.ObjectFactory.class,
    com.sforce.soap.enterprise.sobject.ObjectFactory.class
})
public interface Soap {


    /**
     * Login to the Salesforce.com SOAP Api
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.LoginResponse
     * @throws InvalidIdFault
     * @throws LoginFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "loginResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public LoginResponse login(
        @WebParam(name = "login", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Login parameters)
        throws InvalidIdFault, LoginFault, UnexpectedErrorFault
    ;

    /**
     * Describe an sObject
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSObjectResponse
     * @throws InvalidSObjectFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeSObjectResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSObjectResponse describeSObject(
        @WebParam(name = "describeSObject", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSObject parameters)
        throws InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Describe a number sObjects
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSObjectsResponse
     * @throws InvalidSObjectFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeSObjectsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSObjectsResponse describeSObjects(
        @WebParam(name = "describeSObjects", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSObjects parameters)
        throws InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Describe the Global state
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeGlobalResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeGlobalResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeGlobalResponse describeGlobal(
        @WebParam(name = "describeGlobal", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeGlobal parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Describe all the data category groups available for a given set of types
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeDataCategoryGroupsResponse
     * @throws InvalidSObjectFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeDataCategoryGroupsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeDataCategoryGroupsResponse describeDataCategoryGroups(
        @WebParam(name = "describeDataCategoryGroups", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeDataCategoryGroups parameters)
        throws InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Describe the data category group structures for a given set of pair of types and data category group name
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeDataCategoryGroupStructuresResponse
     * @throws InvalidSObjectFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeDataCategoryGroupStructuresResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeDataCategoryGroupStructuresResponse describeDataCategoryGroupStructures(
        @WebParam(name = "describeDataCategoryGroupStructures", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeDataCategoryGroupStructures parameters)
        throws InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Describes your Knowledge settings, such as if knowledgeEnabled is on or off, its default language and supported languages
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeKnowledgeSettingsResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeKnowledgeSettingsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeKnowledgeSettingsResponse describeKnowledgeSettings(
        @WebParam(name = "describeKnowledgeSettings", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeKnowledgeSettings parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Describe a list of FlexiPage and their contents
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeFlexiPagesResponse
     * @throws InvalidIdFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeFlexiPagesResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeFlexiPagesResponse describeFlexiPages(
        @WebParam(name = "describeFlexiPages", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeFlexiPages parameters)
        throws InvalidIdFault, UnexpectedErrorFault
    ;

    /**
     * Describe the items in an AppMenu
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeAppMenuResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeAppMenuResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeAppMenuResponse describeAppMenu(
        @WebParam(name = "describeAppMenu", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeAppMenu parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Describe Gloal and Themes
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeGlobalThemeResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeGlobalThemeResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeGlobalThemeResponse describeGlobalTheme(
        @WebParam(name = "describeGlobalTheme", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeGlobalTheme parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Describe Themes
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeThemeResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeThemeResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeThemeResponse describeTheme(
        @WebParam(name = "describeTheme", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeTheme parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Describe the layout of the given sObject or the given actionable global page.
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeLayoutResponse
     * @throws InvalidSObjectFault
     * @throws InvalidIdFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeLayoutResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeLayoutResponse describeLayout(
        @WebParam(name = "describeLayout", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeLayout parameters)
        throws InvalidIdFault, InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Describe the layout of the SoftPhone
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSoftphoneLayoutResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeSoftphoneLayoutResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSoftphoneLayoutResponse describeSoftphoneLayout(
        @WebParam(name = "describeSoftphoneLayout", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSoftphoneLayout parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Describe the search view of an sObject
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSearchLayoutsResponse
     * @throws InvalidSObjectFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeSearchLayoutsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSearchLayoutsResponse describeSearchLayouts(
        @WebParam(name = "describeSearchLayouts", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSearchLayouts parameters)
        throws InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Describe a list of objects representing the order and scope of objects on a users search result page
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSearchScopeOrderResponse
     */
    @WebMethod
    @WebResult(name = "describeSearchScopeOrderResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSearchScopeOrderResponse describeSearchScopeOrder(
        @WebParam(name = "describeSearchScopeOrder", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSearchScopeOrder parameters);

    /**
     * Describe the compact layouts of the given sObject
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeCompactLayoutsResponse
     */
    @WebMethod
    @WebResult(name = "describeCompactLayoutsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeCompactLayoutsResponse describeCompactLayouts(
        @WebParam(name = "describeCompactLayouts", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeCompactLayouts parameters);

    /**
     * Describe the approval layouts of the given sObject
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeApprovalLayoutResponse
     */
    @WebMethod
    @WebResult(name = "describeApprovalLayoutResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeApprovalLayoutResponse describeApprovalLayout(
        @WebParam(name = "describeApprovalLayout", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeApprovalLayout parameters);

    /**
     * Describe the ListViews as SOQL metadata for the generation of SOQL.
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeSoqlListViewsResponse
     * @throws InvalidSObjectFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeSoqlListViewsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeSoqlListViewsResponse describeSoqlListViews(
        @WebParam(name = "describeSoqlListViews", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeSoqlListViews parameters)
        throws InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Execute the specified list view and return the presentation-ready results.
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.ExecuteListViewResponse
     */
    @WebMethod
    @WebResult(name = "executeListViewResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public ExecuteListViewResponse executeListView(
        @WebParam(name = "executeListView", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        ExecuteListView parameters);

    /**
     * Describe the tabs that appear on a users page
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeTabsResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeTabsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeTabsResponse describeTabs(
        @WebParam(name = "describeTabs", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeTabs parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Describe all tabs available to a user
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeAllTabsResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "describeAllTabsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeAllTabsResponse describeAllTabs(
        @WebParam(name = "describeAllTabs", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeAllTabs parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Describe the primary compact layouts for the sObjects requested
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribePrimaryCompactLayoutsResponse
     */
    @WebMethod
    @WebResult(name = "describePrimaryCompactLayoutsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribePrimaryCompactLayoutsResponse describePrimaryCompactLayouts(
        @WebParam(name = "describePrimaryCompactLayouts", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribePrimaryCompactLayouts parameters);

    /**
     * Create a set of new sObjects
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.CreateResponse
     * @throws InvalidFieldFault
     * @throws InvalidSObjectFault
     * @throws InvalidIdFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "createResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public CreateResponse create(
        @WebParam(name = "create", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Create parameters)
        throws InvalidFieldFault, InvalidIdFault, InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Update a set of sObjects
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.UpdateResponse
     * @throws InvalidFieldFault
     * @throws InvalidSObjectFault
     * @throws InvalidIdFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "updateResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public UpdateResponse update(
        @WebParam(name = "update", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Update parameters)
        throws InvalidFieldFault, InvalidIdFault, InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Update or insert a set of sObjects based on object id
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.UpsertResponse
     * @throws InvalidFieldFault
     * @throws InvalidSObjectFault
     * @throws InvalidIdFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "upsertResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public UpsertResponse upsert(
        @WebParam(name = "upsert", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Upsert parameters)
        throws InvalidFieldFault, InvalidIdFault, InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Merge and update a set of sObjects based on object id
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.MergeResponse
     * @throws InvalidFieldFault
     * @throws InvalidSObjectFault
     * @throws InvalidIdFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "mergeResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public MergeResponse merge(
        @WebParam(name = "merge", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Merge parameters)
        throws InvalidFieldFault, InvalidIdFault, InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Delete a set of sObjects
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DeleteResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "deleteResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DeleteResponse delete(
        @WebParam(name = "delete", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Delete parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Undelete a set of sObjects
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.UndeleteResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "undeleteResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public UndeleteResponse undelete(
        @WebParam(name = "undelete", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Undelete parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Empty a set of sObjects from the recycle bin
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.EmptyRecycleBinResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "emptyRecycleBinResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public EmptyRecycleBinResponse emptyRecycleBin(
        @WebParam(name = "emptyRecycleBin", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        EmptyRecycleBin parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Get a set of sObjects
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.RetrieveResponse
     * @throws InvalidFieldFault
     * @throws MalformedQueryFault
     * @throws InvalidSObjectFault
     * @throws InvalidIdFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "retrieveResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public RetrieveResponse retrieve(
        @WebParam(name = "retrieve", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Retrieve parameters)
        throws InvalidFieldFault, InvalidIdFault, InvalidSObjectFault, MalformedQueryFault, UnexpectedErrorFault
    ;

    /**
     * Submit an entity to a workflow process or process a workitem
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.ProcessResponse
     * @throws InvalidIdFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "processResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public ProcessResponse process(
        @WebParam(name = "process", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Process parameters)
        throws InvalidIdFault, UnexpectedErrorFault
    ;

    /**
     * convert a set of leads
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.ConvertLeadResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "convertLeadResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public ConvertLeadResponse convertLead(
        @WebParam(name = "convertLead", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        ConvertLead parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Logout the current user, invalidating the current session.
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.LogoutResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "logoutResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public LogoutResponse logout(
        @WebParam(name = "logout", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Logout parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Logs out and invalidates session ids
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.InvalidateSessionsResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "invalidateSessionsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public InvalidateSessionsResponse invalidateSessions(
        @WebParam(name = "invalidateSessions", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        InvalidateSessions parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Get the IDs for deleted sObjects
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.GetDeletedResponse
     * @throws InvalidSObjectFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "getDeletedResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public GetDeletedResponse getDeleted(
        @WebParam(name = "getDeleted", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        GetDeleted parameters)
        throws InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Get the IDs for updated sObjects
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.GetUpdatedResponse
     * @throws InvalidSObjectFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "getUpdatedResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public GetUpdatedResponse getUpdated(
        @WebParam(name = "getUpdated", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        GetUpdated parameters)
        throws InvalidSObjectFault, UnexpectedErrorFault
    ;

    /**
     * Create a Query Cursor
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.QueryResponse
     * @throws InvalidFieldFault
     * @throws MalformedQueryFault
     * @throws InvalidSObjectFault
     * @throws InvalidIdFault
     * @throws UnexpectedErrorFault
     * @throws InvalidQueryLocatorFault
     */
    @WebMethod
    @WebResult(name = "queryResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public QueryResponse query(
        @WebParam(name = "query", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Query parameters)
        throws InvalidFieldFault, InvalidIdFault, InvalidQueryLocatorFault, InvalidSObjectFault, MalformedQueryFault, UnexpectedErrorFault
    ;

    /**
     * Create a Query Cursor, including deleted sObjects
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.QueryAllResponse
     * @throws InvalidFieldFault
     * @throws MalformedQueryFault
     * @throws InvalidSObjectFault
     * @throws InvalidIdFault
     * @throws UnexpectedErrorFault
     * @throws InvalidQueryLocatorFault
     */
    @WebMethod
    @WebResult(name = "queryAllResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public QueryAllResponse queryAll(
        @WebParam(name = "queryAll", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        QueryAll parameters)
        throws InvalidFieldFault, InvalidIdFault, InvalidQueryLocatorFault, InvalidSObjectFault, MalformedQueryFault, UnexpectedErrorFault
    ;

    /**
     * Gets the next batch of sObjects from a query
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.QueryMoreResponse
     * @throws InvalidFieldFault
     * @throws MalformedQueryFault
     * @throws UnexpectedErrorFault
     * @throws InvalidQueryLocatorFault
     */
    @WebMethod
    @WebResult(name = "queryMoreResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public QueryMoreResponse queryMore(
        @WebParam(name = "queryMore", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        QueryMore parameters)
        throws InvalidFieldFault, InvalidQueryLocatorFault, MalformedQueryFault, UnexpectedErrorFault
    ;

    /**
     * Search for sObjects
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.SearchResponse
     * @throws InvalidFieldFault
     * @throws MalformedSearchFault
     * @throws InvalidSObjectFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "searchResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public SearchResponse search(
        @WebParam(name = "search", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        Search parameters)
        throws InvalidFieldFault, InvalidSObjectFault, MalformedSearchFault, UnexpectedErrorFault
    ;

    /**
     * Gets server timestamp
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.GetServerTimestampResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "getServerTimestampResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public GetServerTimestampResponse getServerTimestamp(
        @WebParam(name = "getServerTimestamp", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        GetServerTimestamp parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Set a user's password
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.SetPasswordResponse
     * @throws InvalidIdFault
     * @throws InvalidNewPasswordFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "setPasswordResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public SetPasswordResponse setPassword(
        @WebParam(name = "setPassword", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        SetPassword parameters)
        throws InvalidIdFault, InvalidNewPasswordFault, UnexpectedErrorFault
    ;

    /**
     * Reset a user's password
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.ResetPasswordResponse
     * @throws InvalidIdFault
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "resetPasswordResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public ResetPasswordResponse resetPassword(
        @WebParam(name = "resetPassword", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        ResetPassword parameters)
        throws InvalidIdFault, UnexpectedErrorFault
    ;

    /**
     * Returns standard information relevant to the current user
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.GetUserInfoResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "getUserInfoResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public GetUserInfoResponse getUserInfo(
        @WebParam(name = "getUserInfo", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        GetUserInfo parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Send existing draft EmailMessage
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.SendEmailMessageResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "sendEmailMessageResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public SendEmailMessageResponse sendEmailMessage(
        @WebParam(name = "sendEmailMessage", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        SendEmailMessage parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Send outbound email
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.SendEmailResponse
     * @throws UnexpectedErrorFault
     */
    @WebMethod
    @WebResult(name = "sendEmailResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public SendEmailResponse sendEmail(
        @WebParam(name = "sendEmail", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        SendEmail parameters)
        throws UnexpectedErrorFault
    ;

    /**
     * Perform a series of predefined actions such as quick create or log a task
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.PerformQuickActionsResponse
     */
    @WebMethod
    @WebResult(name = "performQuickActionsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public PerformQuickActionsResponse performQuickActions(
        @WebParam(name = "performQuickActions", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        PerformQuickActions parameters);

    /**
     * Describe the details of a series of quick actions
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeQuickActionsResponse
     */
    @WebMethod
    @WebResult(name = "describeQuickActionsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeQuickActionsResponse describeQuickActions(
        @WebParam(name = "describeQuickActions", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeQuickActions parameters);

    /**
     * Describe the details of a series of quick actions available for the given contextType
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.DescribeAvailableQuickActionsResponse
     */
    @WebMethod
    @WebResult(name = "describeAvailableQuickActionsResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public DescribeAvailableQuickActionsResponse describeAvailableQuickActions(
        @WebParam(name = "describeAvailableQuickActions", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        DescribeAvailableQuickActions parameters);

    /**
     * Retreive the template sobjects, if appropriate, for the given quick action names in a given context
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.enterprise.RetrieveQuickActionTemplatesResponse
     */
    @WebMethod
    @WebResult(name = "retrieveQuickActionTemplatesResponse", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
    public RetrieveQuickActionTemplatesResponse retrieveQuickActionTemplates(
        @WebParam(name = "retrieveQuickActionTemplates", targetNamespace = "urn:enterprise.soap.sforce.com", partName = "parameters")
        RetrieveQuickActionTemplates parameters);

}
